<?xml version="1.0" encoding="UTF-8"?>
<!-- 有警告是因为，没有DTD规则约束 -->
<!DOCTYPE scores[
	<!ELEMENT scores (student *)>
	<!ELEMENT student (name, course, score)>
	<!ATTLIST student id CDATA #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT course (#PCDATA)>
	<!ELEMENT score (#PCDATA)>
	
]>

<scores>
	<student id="1">
		<name>ww</name>
		<course>Java</course>
		<score>99</score>
	</student>
	
	<student id="2">
		<name>aa</name>
		<course>Java</course>
		<score>88</score>
	</student>
</scores>